version: "3"

services:
  rose-master:
    build: ./rose-master
    image: phsong/rose-master:0.0.1
    container_name: rose-master
#    volumes:
#      - rose-mysql:/var/lib/mysql
    ports:
      - "8020:8020"
      - "50070:50070"
      - "50470:50470"
      - "8088:8088"
      - "19888:19888"
      - "3306:3306"
      - "9083:9083"
      - "10000:10000"
      - "16010:16010"
      - "2181:2181"
      - "28080:28080"
      - "8080:8080"
      - "4040:4040"
      - "4000:4000"
      - "18080:18080"
      - "8048:8048"
      - "8091:8091"
  rose-master2:
    build: ./rose-master2
    image: phsong/rose-master2:0.0.1
    container_name: rose-master2
    ports:
      - "50090:50090"
  rose-client:
    build: ./rose-client
    image: phsong/rose-client:0.0.1
    container_name: rose-client
    ports:
      - "50075:50075"
      - "8042:8042"
      - "16030:16030"
      - "8081:8081"
  rose-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - rose-redis:/data
  rose-rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  rose-sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    volumes:
      - rose-redis:/etc/sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 1234Qwer!
  rose-portainer:
    image: portainer/portainer-ce
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - rose-portainer:/data
volumes:
  rose-mysql:
  rose-redis:
  rose-portainer:
