build:
	docker build -t phsong/rose-base:0.0.1 ./rose-base
	docker build -t phsong/rose-master:0.0.1 ./rose-master
	docker build -t phsong/rose-master2:0.0.1 ./rose-master2
	docker build -t phsong/rose-client:0.0.1 ./rose-client
