CREATE DATABASE hive;
CREATE USER 'hive'@'%' IDENTIFIED BY 'Ab123456';
GRANT ALL ON hive.* TO 'hive'@'%';

CREATE DATABASE ke;
CREATE USER 'ke'@'%' IDENTIFIED BY 'Ab123456';
GRANT ALL ON ke.* TO 'ke'@'%';
FLUSH PRIVILEGES;